# Generated by Django 4.2.3 on 2023-07-24 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('scribe_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scribesource',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
